version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test
